/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventasdao.ui.abm;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ventasdao.controladores.CategoriaControlador;
import ventasdao.controladores.IShowException;
import ventasdao.controladores.TipoClienteControlador;
import ventasdao.objetos.Categoria;
import ventasdao.objetos.TipoCliente;
import ventasdao.ui.grilla.GrillaCategoria;
import ventasdao.ui.grilla.GrillaTipoCliente;

/**
 *
 * @author Hugo Chanampe
 */
public class AbmTipoCLiente extends javax.swing.JInternalFrame implements IShowException {

    /**
     * Creates new form AbmCategoria
     */
    private TipoCliente tipoCliente;
    private TipoClienteControlador tipoClienteControlador;
    private GrillaTipoCliente grillaTipoCliente;
    
    public AbmTipoCLiente() {
        initComponents();
        
        tipoClienteControlador = new TipoClienteControlador();
        ArrayList<TipoCliente> tipoClientes = new ArrayList<>();
        
            tipoClienteControlador.addListener(this);

        try {
            tipoClientes = (ArrayList)tipoClienteControlador.listar();
        } catch (Exception e) {
            e.printStackTrace ();
        }

        grillaTipoCliente = new GrillaTipoCliente(tipoClientes);
        jtListadoCategorias.setModel(grillaTipoCliente);
    }
    
    public void limpiarCampos(){
    
    jtfDenominacion.setText("");
    jtfDescripcion.setText("");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfDenominacion = new javax.swing.JTextField();
        jtfDescripcion = new javax.swing.JTextField();
        jbAltaCategoria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListadoCategorias = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jtfId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setText("Nombre");

        jLabel2.setText("Descripcion");

        jbAltaCategoria.setText("Agregar");
        jbAltaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAltaCategoriaMouseClicked(evt);
            }
        });
        jbAltaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaCategoriaActionPerformed(evt);
            }
        });

        jtListadoCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtListadoCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListadoCategoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListadoCategorias);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtfId.setEnabled(false);
        jtfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdActionPerformed(evt);
            }
        });

        jLabel3.setText("Id");

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(240, 150, 150));
        jLabel4.setText("jLabel4");

        jLabel5.setForeground(new java.awt.Color(240, 150, 150));
        jLabel5.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfDenominacion)
                            .addComponent(jtfDescripcion)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbAltaCategoria)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbAltaCategoria)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtListadoCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListadoCategoriasMouseClicked
        
       TipoCliente tipoCliente = grillaTipoCliente.getCategoriaFromRow(jtListadoCategorias.getSelectedRow());
       
       jtfDenominacion.setText(tipoCliente.getNombre());
       jtfDescripcion.setText(tipoCliente.getDescripcion());
       jtfId.setText(tipoCliente.getId().toString() );
       
      
        
    }//GEN-LAST:event_jtListadoCategoriasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            
            // TODO add your handling code here:
            tipoCliente = new TipoCliente();
            
            tipoCliente.setNombre( jtfDenominacion.getText() );
            tipoCliente.setDescripcion( jtfDescripcion.getText() );
            tipoCliente.setId( Integer.parseInt( jtfId.getText() ) );
            
            ClearMensajesDeValidacion();
            if(!ValidarCampos(tipoCliente)){
                return;
            }

            
            
            tipoClienteControlador.modificar(tipoCliente);
        } catch (Exception ex) {
            Logger.getLogger(AbmTipoCLiente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            grillaTipoCliente.vaciar();
            grillaTipoCliente.reemplazarLista((ArrayList)tipoClienteControlador.listar());
            jtListadoCategorias.updateUI();
            //jtListadoCategorias.setModel(new GrillaTipoCliente( (ArrayList)tipoClienteControlador.listar() ));
        } catch (Exception ex) {
            Logger.getLogger(AbmTipoCLiente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdActionPerformed

    private void jbAltaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaCategoriaActionPerformed

        // TODO add your handling code here:
        tipoCliente = new TipoCliente();

        tipoCliente.setNombre(jtfDenominacion.getText());
        tipoCliente.setDescripcion(jtfDescripcion.getText());
        
        ClearMensajesDeValidacion();
        
        if(!ValidarCampos(tipoCliente)){
            return;
        }
        
        
        

        try {
            tipoClienteControlador.crear(tipoCliente);
            
            grillaTipoCliente.vaciar();
            grillaTipoCliente.reemplazarLista((ArrayList)tipoClienteControlador.listar());
            jtListadoCategorias.updateUI();
            //jtListadoCategorias.setModel(new GrillaTipoCliente( (ArrayList) tipoClienteControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmTipoCLiente.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jbAltaCategoriaActionPerformed

    private void jbAltaCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAltaCategoriaMouseClicked

    }//GEN-LAST:event_jbAltaCategoriaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // TODO add your handling code here:
       try {
            // TODO add your handling code here:
            
            // TODO add your handling code here:
            tipoCliente = new TipoCliente();
           
            tipoCliente.setId( Integer.parseInt( jtfId.getText() ) );
            
            tipoClienteControlador.eliminar(tipoCliente);
        } catch (Exception ex) {
            
            javax.swing.JOptionPane.showMessageDialog(this, "The message!", "This is supposed to be the MessageBox title.", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(AbmCategoria.class.getName()).log(Level.SEVERE, null, ex);
            
            
        }
        
        try {
            //jtListadoCategorias.setModel( new GrillaCategoria( categoriaControlador.listar() ));
            grillaTipoCliente.vaciar();
            grillaTipoCliente.reemplazarLista(tipoClienteControlador.listar());
            jtListadoCategorias.updateUI();
        } catch (Exception ex) {
            Logger.getLogger(AbmCategoria.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAltaCategoria;
    private javax.swing.JTable jtListadoCategorias;
    private javax.swing.JTextField jtfDenominacion;
    private javax.swing.JTextField jtfDescripcion;
    private javax.swing.JTextField jtfId;
    // End of variables declaration//GEN-END:variables

    
    public void ClearMensajesDeValidacion(){
        jLabel4.setText("");
        jLabel5.setText("");
    }
    
    public boolean ValidarCampos(TipoCliente tipoCliente ){

        boolean valido = true; 
        
        if( tipoCliente.getNombre().trim().isEmpty() || tipoCliente.getNombre().trim().length() < 3 ){
            jLabel4.setText("El Nombre está vacío o tiene menos de 3 caracteres.");
            valido = false;
        } 
        
        if(tipoCliente.getDescripcion().trim().isEmpty() || tipoCliente.getDescripcion().trim().length() < 3 ){
            jLabel5.setText("Descripción está vacío o tiene menos de 3 caracteres.");
            valido = false; 
        }

        return valido;
    }
    
    
    @Override
    public void ShowException(String message) {
        javax.swing.JOptionPane.showMessageDialog(this,message, "Ha ocurrido un error!", JOptionPane.ERROR_MESSAGE);
    }
}
